### ISSUE TITLE
Omit level buttons until necessary

### ISSUE THREAD

**Issue by Kebap** [Delwing/mudlet-map-reader#2]
Great tool!

Only one minor beauty improvement:

If there is only one level in the map, do not show only zero, which will then do nothing.
Only show zero, one, minus one, etc. when you can actually change between levels.

![image](https://user-images.githubusercontent.com/117238/90035613-49508000-dcc2-11ea-93dc-999280f9d5f8.png)

**Comment by demonnic** [comment]
yeah, I've been meaning to do some work around that part of the display, right now if you have a 40 level tower that display gets nuts.

**Comment by Delwing** [comment]
Included in newest version.
Additionally please refer to: https://github.com/Delwing/mudlet-map-browser 
There is CD workflow set up, that will provide .mpackage versions of generic version of this package (with english translation)
