### ISSUE TITLE
Stub up/down not shown

### ISSUE THREAD

**Issue by Kebap** [Delwing/mudlet-map-reader#5]
In game:

![image](https://user-images.githubusercontent.com/117238/123528145-9aecd800-d6e5-11eb-812e-106176bf3180.png)

In browser:

![image](https://user-images.githubusercontent.com/117238/123528156-ab9d4e00-d6e5-11eb-8130-aec559f10741.png)

**Comment by Delwing** [comment]
Thanks for pointing that out. 

Took a bit time but I was rewriting rendering code so it can be reused at server side rendering as well. I still have to refactor a bit, but I've just pushed updated version, that fixes that issue.

Couldn't recreate exactly pattern inside triangle therefore empty triangle means stub, one filled means working exit.
