### ISSUE TITLE
Door displayed wrong when upstairs

### ISSUE THREAD

**Issue by Kebap** [Delwing/mudlet-map-reader#6]
I deleted the example later, so can't show right now.
Make a room connection with a door, then move one of the rooms to another Z-level.

In browser, the square representing the door will be drawn inside the square representing the room.
In game, the square is drawn on the exit line connecting the two rooms, just like when the rooms were on the same Z-level.

**Comment by Delwing** [comment]
Thanks for pointing that out. 

Took a bit time but I was rewriting rendering code so it can be reused at server side rendering as well. I still have to refactor a bit, but I've just pushed updated version, that fixes that issue.

![image](https://user-images.githubusercontent.com/3740628/133607375-477e6f75-c924-4bf2-b980-d8a4227ac75c.png)
